name: tenanta
description: A property management system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.25
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.0
  url_launcher: ^6.1.14
  url_launcher_web: ^2.0.19
  image: ^4.1.3
  intl: ^0.19.0
  json_annotation: ^4.8.1
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
